### ISSUE TITLE
Regarding Joint Training

### ISSUE THREAD

**Issue by LeiWangCV** [ZcsrenlongZ/ZoomGS#4]
Thanks for your great work. I think the data for UW and W in the paper should correspond because ZoomGS can generate a series of scaled images from UW to W, but your open-source data is not. Will this have an impact on joint training, or do UW and W not need to correspond in quantity and position during the training process? I hope you can help me clarify this confusion. Thank you again for your work

**Comment by ZcsrenlongZ** [comment]
In our experiments, we find that directly inputting UW (x0.6) and W (x1.0) images to the  frame interpolation (FI) model makes it difficult to produce high-quality transition sequences. It may be because the positions of UW and W images are quite different (W image is only the center part of UW image). To alleviate this problem, when transition from the UW (x0.6) image to W (x1.0) image, we first arbitrary upscale the UW image from x0.6 to 0.85,  then perform frame interpolation between UW (x0.85) image and W (x1.0) image. I hope the statements can address your confusion.

**Comment by LeiWangCV** [comment]
Thank you for your reply. I would like to know if the lack of any correspondence between UW and W data in camera position during the training of ZoomGS affects its performance. This is because images of different resolutions (different camera parameters) participate in GS training together, and the GS effect deteriorates. This is reflected in the third row of the results in Table 2, and the fourth row indicates that ZoomGS has overcome this limitation.
My question is: In the process of training ZoomGS, the inconsistency in the number, position, and content of UW and W images does not affect the training. In the inference stage, virtual Pv, Kv, and camera encoding e can be obtained by interpolating P and K between UW and W, and sequence images from UW to W. Is my understanding correct?
Thank you for your help.

**Comment by ZcsrenlongZ** [comment]
Is your question whether it is possible to train ZoomGS using unpaired collected UW and W images? In other words, the W image is not corresponding to the UW image?

**Comment by LeiWangCV** [comment]
Yes, I collected a set of paired UW and W data myself, as well as your open-source data, but I have doubts about whether they are paired or not

**Comment by ZcsrenlongZ** [comment]
The UW and W image should be paired. For a scene, we collected 15 UW and W paires (UW 001~UW015, W001~W015).Due to the narrower FOV of W camera, surrounding areas in the UW image are not seen in the corresponding W image. To cover these areas, we additionally capture 6 images with W camera (W016~W021).

**Comment by ZcsrenlongZ** [comment]
The UW and W image should be paired. For a scene, we collected 15 UW and W paires (UW 001 to UW015, W001 to W015).Due to the narrower FOV of W camera, surrounding areas in the UW image are not seen in the corresponding W image. To cover these areas, we additionally capture 6 images with W camera (W016 to W021).

**Comment by LeiWangCV** [comment]
I understand, thank you again for your help, and I wish you a happy life.
